FROM cyberdojofoundation/gplusplus:95ca4b2
LABEL maintainer=jon@jaggersoft.com

RUN mkdir /fff
COPY fff.h /fff
COPY install.sh .
RUN ./install.sh && rm ./install.sh
COPY red_amber_green.rb /usr/local/bin
