FROM cyberdojofoundation/gcc:ee0bdcd
LABEL maintainer=james@wingman-sw.com

RUN apk add --no-cache gcc g++ musl-dev make \
			autoconf automake git libtool unzip

COPY install-cpputest.sh .
RUN ./install-cpputest.sh && rm ./install-cpputest.sh

COPY install-legacy-build.sh .
RUN ./install-legacy-build.sh && rm ./install-legacy-build.sh

COPY red_amber_green.rb /usr/local/bin

# Don't forget to add new files to .dockerignore
RUN mkdir /fff
COPY fff.h /fff
RUN mkdir /wingman
COPY tdd-build.sh /wingman

ENV TDD_BUILD=/wingman/tdd-build.sh
ENV LEGACY_BUILD=/legacy-build/legacy-build.sh
ENV CPPUTEST_HOME=/cpputest

RUN apk del git unzip
